### ISSUE TITLE
https://eplprinter.azurewebsites.net/ don't refresh rendering

### ISSUE THREAD

**Issue by MatizMazzoni** [neodynamic/EPL-Printer-Emulator-SDK#1]
For a few days it has not been possible to update the rendered label: changes to the dimensions and code are ignored (unless you operate by browser inspector)

**Comment by neodynamic** [comment]
Hi,

Could you elaborate a bit more about the issue? How to reproduce it?

**Comment by MatizMazzoni** [comment]
Now everything is working properly.
