### ISSUE TITLE
Emulator gives "Index was outside the bounds of the array" error

### ISSUE THREAD

**Issue by deakjahn** [neodynamic/EPL-Printer-Emulator-SDK#2]
I started with the attached ZPL test file and used https://labelary.com/viewer.html to convert it to EPL. Neither https://eplprinter.azurewebsites.net nor your .NET SDK (that obviously powers the first) accepts it, both return with the error above. I have no EPL printer so I can't vouch for the correctness of the contents (graphically it's far from perfect but the problem is with displaying it in the first place), although a cursory look suggests it's all right.

[test.zip](https://github.com/user-attachments/files/15519445/test.zip)

**Comment by neodynamic** [comment]
Thanks for reporting the issue. It was just fixed. Update the NuGet ref or our package and/or try the online demo again.
